### ISSUE TITLE
Search function on request manager

### ISSUE THREAD

**Issue by geethmaka** [smdnipun/SMD-Distributors-Automated-System#154]

**Comment by prahasR** [comment]
Hi @geethmaka, is the issue still open? Can you please elaborate a little more over this. What files are needed to be changed and what exactly is the problem? I had worked with `MySQL` earlier.

**Comment by geethmaka** [comment]
> Hi @geethmaka, is the issue still open? Can you please elaborate a little more over this. What files are needed to be changed and what exactly is the problem? I had worked with `MySQL` earlier.

Hello @prahasR Thank you for your interest in our project. But please note that this a project dedicated to a university event and we are not accepting any other contributors at the moment. I hope you understand the situation. Thank you.
